layout: sidebar
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    archived: false
    forks: true
    projects:
    # - repo-name

social_media:
  # behance: your_username
  # dribbble: your_username
  facebook: sabbirrrrr
  # hackerrank: your_username
  instagram: sabbirrrrrr
  # keybase: your_username
  linkedin: sabbirrrrr
  # mastodon: your_username
  medium: sabbirshawon
  stackoverflow: 11653799
  # telegram: your_username
  twitter: sabbirs93
  # unsplash: your_username
  # vk: your_username
  website: https://sabbirshawon.github.io/
  # youtube: 

topics:
  - name: ReactJS
    web_url: https://github.com/topics/reactjs
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/react/react.png

  - name: JavaScript
    image_url: https://upload.wikimedia.org/wikipedia/commons/6/6a/JavaScript-logo.png
    
  - name: NodeJS
    web_url: https://github.com/topics/nodejs
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/nodejs/nodejs.png
